// AIDEN Chrome Extension Content Script

const OBSERVER_CONFIG = {
  childList: true,
  subtree: true,
};

// This flag tracks if the last inserted text was from AIDEN.
let anAnswerWasInsertedByAiden = false;
let currentPostId = null;


// --- ALL FUNCTION DEFINITIONS ---

// --- 1. DATA EXTRACTION FUNCTIONS ---

function getContextualData(targetContainer) {
  try {
    const postId = window.location.pathname.match(/post\/(\d+)/)?.[1];
    if (!postId) return null;

    const title = document.querySelector('#postViewSummaryId')?.innerText.trim();
    const mainContent = document.querySelector('#qaContentViewId .render-html-content')?.innerText.trim();
    const instructorAnswer = document.querySelector('article[data-id="i_answer"] .render-html-content')?.innerText.trim() || '';
    const tags = Array.from(document.querySelectorAll('#folder_select .folder_button')).map(btn => btn.innerText.trim());

    const tagsString = `TAGS: [${tags.join(', ')}]`;
    let uniqueId = postId;
    let llm_input = `${tagsString}\n\nQUESTION: ${mainContent}`;
    let isFollowup = false;

    if (targetContainer && targetContainer.matches('.followup')) {
      isFollowup = true;
      uniqueId = `${postId}_${targetContainer.id}`;
      let followupHistory = [];
      const allFollowups = document.querySelectorAll('.followup');

      for (const followup of allFollowups) {
        const questionEl = followup.querySelector(':scope > .followup_content_wrapper .render-html-content');
        const answerEl = followup.querySelector(':scope .followup_reply .render-html-content');

        if (questionEl) {
          followupHistory.push(`FOLLOW-UP QUESTION: ${questionEl.innerText.trim()}`);
        }
        if (answerEl) {
          const answerClone = answerEl.cloneNode(true);
          const disclaimer = answerClone.querySelector('b');
          if (disclaimer && disclaimer.innerText.includes('response generated by AI')) {
            disclaimer.remove();
            answerClone.querySelector('br')?.remove();
          }
          followupHistory.push(`PREVIOUS ANSWER: ${answerClone.innerText.trim()}`);
        }
        
        if (followup.id === targetContainer.id) break;
      }
      
      llm_input = [
        tagsString,
        `ORIGINAL QUESTION: ${mainContent}`,
        instructorAnswer ? `INSTRUCTOR'S ANSWER TO MAIN QUESTION: ${instructorAnswer}` : '',
        ...followupHistory
      ].filter(Boolean).join('\n\n---\n\n');
    }

    return { postId, uniqueId, llm_input, tags, isFollowup, title, mainContent, instructorAnswer };

  } catch (e) {
    console.error("AIDEN: Failed to extract contextual data.", e);
    return null;
  }
}

// --- 2. UI MODAL FUNCTIONS ---

function showLoadingModal() {
  hideLoadingModal();
  const modal = document.createElement('div');
  modal.id = 'aiden-loading-modal';
  modal.style.cssText = `
    position: fixed; top: 20px; right: 50px; background-color: #2c3e50; color: white;
    padding: 15px 25px; border-radius: 8px; box-shadow: 0 4px 15px rgba(0,0,0,0.2);
    z-index: 10001; display: flex; align-items: center; font-family: sans-serif; font-size: 14px;
  `;
  const spinner = document.createElement('div');
  spinner.style.cssText = `
    width: 20px; height: 20px; border: 3px solid rgba(255, 255, 255, 0.3);
    border-radius: 50%; border-top-color: #3498db; animation: spin 1s linear infinite; margin-right: 15px;
  `;
  const styleSheet = document.createElement("style");
  styleSheet.innerText = `@keyframes spin { to { transform: rotate(360deg); } }`;
  document.head.appendChild(styleSheet);
  modal.appendChild(spinner);
  modal.append('AIDEN is generating the response...');
  document.body.appendChild(modal);
}

function hideLoadingModal() {
  const modal = document.getElementById('aiden-loading-modal');
  if (modal) modal.remove();
}

function showRatingModal(submitButton, targetContainer) {
  if (document.getElementById('aiden-rating-modal')) return;

  const modal = document.createElement('div');
  modal.id = 'aiden-rating-modal';
  modal.className = 'aiden-modal';
  modal.innerHTML = `
    <div class="aiden-modal-content">
      <div class="aiden-modal-header"><h3>How helpful was the AI's answer?</h3></div>
      <div class="aiden-modal-body">
        <div class="aiden-stars-container">
          <span class="aiden-star" data-value="1">★</span> <span class="aiden-star" data-value="2">★</span>
          <span class="aiden-star" data-value="3">★</span> <span class="aiden-star" data-value="4">★</span>
          <span class="aiden-star" data-value="5">★</span>
        </div>
      </div>
      <div class="aiden-modal-footer">
        <button id="aiden-rating-submit" class="aiden-modal-submit-btn" disabled>Submit Rating</button>
      </div>
    </div>
  `;
  document.body.appendChild(modal);

  const stars = modal.querySelectorAll('.aiden-star');
  const ratingSubmitBtn = modal.querySelector('#aiden-rating-submit');
  let selectedRating = 0;

  stars.forEach(star => {
    star.addEventListener('click', () => {
      selectedRating = parseInt(star.dataset.value, 10);
      ratingSubmitBtn.disabled = false;
      stars.forEach(s => s.classList.toggle('filled', parseInt(s.dataset.value, 10) <= selectedRating));
    });
  });

  ratingSubmitBtn.addEventListener('click', () => {
    const frame = targetContainer.querySelector('iframe.tox-edit-area__iframe');
    const finalAnswer = frame ? frame.contentDocument.body.innerHTML : '';
    // This is safe now because getContextualData is defined before this function is
    const context = getContextualData(targetContainer); 

    const payload = {
      post_id: context.uniqueId,
      rating: selectedRating,
      submitted_answer: finalAnswer,
      llm_input: context.llm_input,
      tags: context.tags
    };
    chrome.runtime.sendMessage({ action: "submitRating", payload });

    modal.remove();
    submitButton.click();
  });
}

// --- 3. CORE LOGIC FUNCTIONS ---

function insertAidenResponse(answer, targetContainer) {
  if (!targetContainer) return alert("AIDEN Error: Could not find the target answer box.");
  const frame = targetContainer.querySelector('iframe.tox-edit-area__iframe');
  if (!frame) return alert("AIDEN Error: Could not find the editor iframe.");
  const editorBody = frame.contentDocument?.body;
  if (!editorBody) return alert("AIDEN Error: Could not access the editor's body.");

  editorBody.innerHTML = `<b>❗️This is the response generated by AI. TAs please review the answer carefully before submitting it.❗️</b><br><br>${answer}`;
  anAnswerWasInsertedByAiden = true;
}

function initiateGetResponse(buttonEl) {
  const targetContainer = buttonEl.closest('article, .followup');
  const context = getContextualData(targetContainer);
  if (!context) return alert('AIDEN Error: Could not gather context for this action.');

  const { uniqueId, llm_input, tags, postId } = context;

  chrome.runtime.sendMessage({ action: "proxyFetch", endpoint: `/get_response/${uniqueId}` }, (data) => {
    if (chrome.runtime.lastError) {
      console.error(chrome.runtime.lastError.message);
      return alert("AIDEN Error: Could not communicate with the background script.");
    }

    if (data?.response) {
      insertAidenResponse(data.response.output || data.response.answer, targetContainer);
    } else {
      showLoadingModal();
      const payload = { post_id: uniqueId, llm_input, tags, original_post_id: postId };
      
      chrome.runtime.sendMessage({ action: "triggerGeneration", payload }, () => {
        if (chrome.runtime.lastError) {
          console.error(chrome.runtime.lastError.message);
          hideLoadingModal();
          return alert("AIDEN Error: Could not trigger AI generation.");
        }

        const pollInterval = setInterval(() => {
          chrome.runtime.sendMessage({ action: "proxyFetch", endpoint: `/get_response/${uniqueId}` }, (pollData) => {
            if (chrome.runtime.lastError) {
              console.error(chrome.runtime.lastError.message);
              clearInterval(pollInterval);
              hideLoadingModal();
              return;
            }

            if (pollData?.response) {
              clearInterval(pollInterval);
              insertAidenResponse(pollData.response.output || pollData.response.answer, targetContainer);
              setTimeout(hideLoadingModal, 100);
            }
          });
        }, 3000);
      });
    }
  });
}

function attachToSubmitButton(submitButton) {
  if (!submitButton || submitButton.dataset.aidenAttached) return;

  submitButton.dataset.aidenAttached = 'true';
  submitButton.addEventListener('click', (event) => {
    if (anAnswerWasInsertedByAiden) {
      event.preventDefault();
      event.stopPropagation();
      
      const targetContainer = submitButton.closest('article, .followup');
      showRatingModal(submitButton, targetContainer);
      
      anAnswerWasInsertedByAiden = false;
    }
  }, true);
}

function injectAidenButton(footer) {
    const buttonContainer = footer.querySelector('.d-flex.gap-1');
    if (!buttonContainer || footer.querySelector('.aiden-button')) return;

    const button = document.createElement('button');
    button.className = 'btn btn-ghost btn-sm aiden-button';
    button.innerHTML = '✨ Get AIDEN Response';
    button.style.marginLeft = '10px';
    button.onclick = (e) => {
        e.preventDefault();
        initiateGetResponse(e.target);
    };
    buttonContainer.appendChild(button);
}

function runInjector() {
    document.querySelectorAll('article[data-id="i_answer"] > footer, .followup footer').forEach(footer => {
        injectAidenButton(footer);
        const submitButton = footer.querySelector('button[id*="_submit"]');
        attachToSubmitButton(submitButton);
    });
}

// --- SCRIPT EXECUTION & OBSERVER ---

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "getQuestionData") {
    const activeIframe = document.activeElement?.tagName === 'IFRAME' ? document.activeElement : null;
    const activeContainer = activeIframe ? (activeIframe.closest('.followup') || activeIframe.closest('article')) : document.querySelector('article[data-id="i_answer"]');
    sendResponse(getContextualData(activeContainer));
  }
  return true;
});

const observer = new MutationObserver(() => {
    runInjector();
    const postIdEl = document.querySelector('.post_number_copy');
    const newPostId = postIdEl ? postIdEl.innerText.replace('@', '') : null;
    if (newPostId && newPostId !== currentPostId) {
        currentPostId = newPostId;
        anAnswerWasInsertedByAiden = false;
    }
});

observer.observe(document.body, OBSERVER_CONFIG);
runInjector();