// AIDEN Chrome Extension Content Script

const OBSERVER_CONFIG = {
  childList: true,
  subtree: true,
};

let currentPostId = null;
let aidenResponse = null;
let anAnswerWasInsertedByAiden = false;

// --- UTILITY FUNCTIONS ---

function extractPostId() {
  const postIdMatch = window.location.pathname.match(/post\/(\d+)/);
  return postIdMatch ? postIdMatch[1] : null;
}

function extractPostData() {
  try {
    const title = document.querySelector('#postViewSummaryId')?.innerText?.trim();
    const content = document.querySelector('.render-html-content')?.innerText?.trim();
    const tagButtons = [...document.querySelectorAll('#folder_select .folder_button')];
    const tags = tagButtons.map((btn) => btn.innerText.trim());
    const postId = extractPostId();
    const url = window.location.href;

    if (postId && title && content) {
      return { postId, title, content, tags, url };
    }
    return null;
  } catch (err) {
    console.error('[AIDEN] Error extracting post data:', err);
    return null;
  }
}

// --- RATING MODAL LOGIC ---

function showRatingModal(submitButton) {
  if (document.querySelector('.aiden-modal')) return;

  const modal = document.createElement('div');
  modal.className = 'aiden-modal';
  modal.innerHTML = `
    <div class="aiden-modal-content">
      <div class="aiden-modal-header"><h3>How helpful was the AI's answer?</h3></div>
      <div class="aiden-modal-body">
        <div class="aiden-stars-container">
          <span class="aiden-star" data-value="1">★</span>
          <span class="aiden-star" data-value="2">★</span>
          <span class="aiden-star" data-value="3">★</span>
          <span class="aiden-star" data-value="4">★</span>
          <span class="aiden-star" data-value="5">★</span>
        </div>
      </div>
      <div class="aiden-modal-footer">
        <button id="aiden-rating-submit" class="aiden-modal-submit-btn" disabled>Submit Rating</button>
      </div>
    </div>
  `;
  document.body.appendChild(modal);

  const stars = modal.querySelectorAll('.aiden-star');
  const submitBtn = modal.querySelector('#aiden-rating-submit');
  let selectedRating = 0;

  stars.forEach(star => {
    star.addEventListener('click', () => {
      selectedRating = parseInt(star.dataset.value, 10);
      submitBtn.disabled = false;
      stars.forEach(s => s.classList.toggle('filled', parseInt(s.dataset.value, 10) <= selectedRating));
    });
  });

  submitBtn.addEventListener('click', () => {
    const postData = extractPostData();
    
    // Get the final content from the editor iframe
    let submittedAnswer = '';
    const frame = document.getElementById("i_answer_edit_ifr");
    if (frame) {
      const iframeDoc = frame.contentDocument || frame.contentWindow.document;
      submittedAnswer = iframeDoc.body.innerHTML;
    }

    if (postData) {
      chrome.runtime.sendMessage({
        action: "submitRating",
        payload: { 
          postId: postData.postId, 
          rating: selectedRating,
          submittedAnswer: submittedAnswer // Add the answer to the payload
        },
      });
    }
    
    submitButton.click();
    document.body.removeChild(modal);
  });
}

// --- CORE EXTENSION LOGIC ---

function insertAidenResponse(answer) {
  const frame = document.getElementById("i_answer_edit_ifr");
  if (!frame) {
    alert("Could not find the Piazza answer box. Please click into the answer field to activate it, and then try again.");
    return;
  }

  const iframeDoc = frame.contentDocument || frame.contentWindow.document;
  const editor = iframeDoc.querySelector('body#tinymce'); 

  if (!editor) {
    alert("Could not find the editor within the answer box. Please try again.");
    return;
  }
  
  const responseHtml = `<b>❗️This is the response generated by AI. TAs please review the answer carefully before submitting it.❗️</b><br><br>${answer}`;
  editor.innerHTML = responseHtml;
  editor.dispatchEvent(new Event('input', { bubbles: true, cancelable: true }));

  anAnswerWasInsertedByAiden = true;
}


function fetchAndInsertResponse() {
  const postData = extractPostData();
  if (!postData || !postData.postId) {
    alert('Could not get post data to fetch response.');
    return;
  }
  chrome.runtime.sendMessage({
      action: "proxyFetch",
      endpoint: `/get_response/${postData.postId}`,
      method: "GET",
    },
    (data) => {
      if (data?.response) {
        aidenResponse = data.response;
        insertAidenResponse(aidenResponse.output || aidenResponse.answer || '');
      } else {
        alert('No response available. Please generate one from the popup first.');
      }
    }
  );
}

function injectAidenButton() {
  if (document.getElementById('aiden-button')) return;

  const targetArea = document.querySelector('article#qaContentViewId footer .row > div');
  if (targetArea) {
    const aidenButton = document.createElement('button');
    aidenButton.id = 'aiden-button';
    aidenButton.className = 'btn btn-ghost btn-sm';
    aidenButton.innerHTML = '✨ Get AIDEN Response';
    aidenButton.style.marginLeft = '10px';
    aidenButton.style.whiteSpace = 'nowrap';
    aidenButton.addEventListener('click', (e) => {
      e.preventDefault();
      fetchAndInsertResponse();
    });
    targetArea.appendChild(aidenButton);
  }
}

function attachToSubmitButton() {
  const submitButton = document.querySelector('#i_answer_edit_submit');

  if (submitButton && !submitButton.dataset.aidenAttached) {
    submitButton.dataset.aidenAttached = 'true';

    submitButton.addEventListener('click', (e) => {
      if (anAnswerWasInsertedByAiden) {
        e.preventDefault();
        e.stopPropagation();
        showRatingModal(submitButton);
        anAnswerWasInsertedByAiden = false;
      }
    }, true); 
  }
}

// --- LISTENERS AND OBSERVERS ---

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "getQuestionData") {
    sendResponse(extractPostData());
    return true;
  }
  if (request.action === "insertAidenResponse") {
    fetchAndInsertResponse();
  }
});

const observer = new MutationObserver(() => {
  injectAidenButton();
  attachToSubmitButton();
  const newPostId = extractPostId();
  if (newPostId !== currentPostId) {
    currentPostId = newPostId;
    anAnswerWasInsertedByAiden = false;
  }
});

observer.observe(document.body, OBSERVER_CONFIG);